name: brock
favicon: null
layout_spectrum: 0.35249675111845136
typography_spectrum: 0.686846672790125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8919939137995243
  lightness: 0.6430356244090945
  saturation: 0.9073508651927114
  rhythmicContrast: 0.6727472834754735
purpose: []
